[tool.black]
line-length = 120
target-version = ['py310']

[tool.pytest.ini_options]
flake8-max-line-length = 120
flake8-ignore = ["E203", "W503"]  # See https://github.com/PyCQA/pycodestyle/issues/373
addopts = "--flake8 --mypy --isort -n auto"
filterwarnings = [
    "error",
    "ignore:Please use `triu` from the `scipy:DeprecationWarning",  # gensim needs an update
    "ignore:`cached_download`",  # flair 0.12+ should solve this.
    "ignore:SelectableGroups dict interface is deprecated. Use select.",  # deprecations on python 3.10
    "ignore:The distutils package is deprecated and slated for removal in Python 3.12.:DeprecationWarning",  # deprecations on python 3.10
]  # Convert all warnings to errors, imo warnings that are not treated as errors will be ignored by most people.
# My approach is to throw an error and let the programmar check if the error is intended (then add it to the filterwarnings) or not (then fix it!)



[tool.mypy]
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true
warn_unused_ignores = true
warn_no_return = true

[tool.isort]
profile = "black"
